#!/usr/bin/env bash
import sys

def factorize_number(n):
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factors.append((i, n // i))
    return factors

def main(filename):
    try:
        with open(filename, 'r') as file:
            for line in file:
                n = int(line.strip())
                factor_pairs = factorize_number(n)
                for pair in factor_pairs:
                    print(f"{n}={pair[0]}*{pair[1]}")
    except FileNotFoundError:
        print(f"File '{filename}' not found.")
    except ValueError:
        print("Invalid data in the file. All lines should contain valid natural numbers greater than 1.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        filename = sys.argv[1]
        main(filename)
